version: "3.5"

services:
  bitcoind:
    build: bitcoin
    command: /root/.bitcoin/run.sh
    volumes:
      - ${COINS_DIR}/.bitcoin:/root/.bitcoin/
      - ./bitcoin/run.sh:/root/.bitcoin/run.sh
    environment:
      - TESTNET=1
    networks:
      - coins


  litecoind:
    build: litecoin
    command: /root/.litecoin/run.sh
    volumes:
      - ${COINS_DIR}/.litecoin:/root/.litecoin/
      - ./litecoin/run.sh:/root/.litecoin/run.sh
    environment:
      - TESTNET=1
    networks:
      - coins

#  geth:
#    build: ethereum
#    command: sh /root/.ethereum/run.sh
#    volumes:
#      - ${COINS_DIR}/.ethereum:/root/.ethereum/
#      - ./ethereum/run.sh:/root/.ethereum/run.sh
#    environment:
#      - TESTNET=1
#    networks:
#      - coins
  dashd:
    build: dash
    command: /root/.dashcore/run.sh
    volumes:
      - ${COINS_DIR}/.dash:/root/.dashcore/
      - ./dash/run.sh:/root/.dashcore/run.sh
    environment:
      - TESTNET=1
    networks:
      - coins

networks:
  coins:
    external: true
