version: "3.5"

services:
  bitcoind:
    build: bitcoin
    command: /root/.bitcoin/run.sh
    environment:
      TESTNET: 1
    volumes:
      - ${LEDGERS_DIR}/btc:/root/.bitcoin/
      - ./bitcoin/bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - ./bitcoin/run.sh:/root/.bitcoin/run.sh
    networks:
      - coins
    ports:
      - 18332:18332


  litecoind:
    build: litecoin
    command: /root/.litecoin/run.sh
    volumes:
      - ${LEDGERS_DIR}/ltc:/root/.litecoin/
      - ./litecoin/litecoin.conf:/root/.litecoin/litecoin.conf
      - ./litecoin/run.sh:/root/.litecoin/run.sh
    environment:
      TESTNET: 1
    networks:
      - coins
    ports:
      - 19332:19332

networks:
  coins:
    external: true
