version: "3.4"

services:
  bitcoind:
    build: bitcoin
    command: bash -c "bitcoind && sleep 5d"
    volumes:
      - bitcoin-data:/root/.bitcoin/

  litecoind:
    build: litecoin
    command: bash -c "sleep 5d"
    ports:
      - 19332:19332
    volumes:
      - litecoin-data:/opt/litecoin/


volumes:
  bitcoin-data:
    name: ${BITCOIN_DATA} # Real ending name
    external: false
  litecoin-data:
    name: ${LITECOIN_DATA} # Real ending name
    external: false