FROM ubuntu:18.04

RUN apt-get update && apt-get install -y wget
RUN wget https://download.litecoin.org/litecoin-0.18.1/linux/litecoin-0.18.1-x86_64-linux-gnu.tar.gz
RUN tar -xvf litecoin-0.18.1-x86_64-linux-gnu.tar.gz