FROM ubuntu:18.04

RUN apt-get update && apt-get install wget -y
RUN wget https://bitcoin.org/bin/bitcoin-core-0.21.0/bitcoin-0.21.0-x86_64-linux-gnu.tar.gz
RUN tar -xvf bitcoin-0.21.0-x86_64-linux-gnu.tar.gz
